export const carColors = [
  { label: "Черный", value: "black" },
  { label: "Белый", value: "white" },
  { label: "Серебристый", value: "silver" },
  { label: "Серый", value: "gray" },
  { label: "Синий", value: "blue" },
  { label: "Красный", value: "red" },
  { label: "Зеленый", value: "green" },
  { label: "Золотистый", value: "gold" },
  { label: "Коричневый", value: "brown" },
  { label: "Оранжевый", value: "orange" },
  { label: "Желтый", value: "yellow" },
  { label: "Бежевый", value: "beige" },
  { label: "Фиолетовый", value: "purple" },
  { label: "Розовый", value: "pink" },
  { label: "Темно-синий", value: "dark-blue" },
  { label: "Темно-серый", value: "dark-gray" },
  { label: "Темно-красный", value: "dark-red" },
  { label: "Темно-зеленый", value: "dark-green" },
  { label: "Темно-бежевый", value: "dark-beige" },
  { label: "Темно-черный", value: "dark-black" },
];
